#!/usr/bin/env bash

if [ -d test/libs/bats ]; then
  ( 
    echo "Update bats-core, support, assert, file and mock submodules."
    # Initialize all the submoudules as listed in .gitmodules and force pull all of them.
    git config -f .gitmodules --list | 
      awk -F= '$1 ~ /.path$/ {print $2}' | 
        xargs rm -rf
    # Repopulate the test/libs directories
    git submodule update
    cd test/libs/bats
      ./install.sh
  )
else
  git submodule add https://github.com/bats-core/bats-core.git test/libs/bats
  git submodule add https://github.com/jasonkarns/bats-assert-1 test/libs/bats-assert
  git submodule add https://github.com/jasonkarns/bats-support test/libs/bats-support
  git submodule add https://github.com/ztombol/bats-file test/libs/bats-file
  git submodule update --init --recursive
  git commit -m 'Add bats-support library'
  cd test/libs/bats
    ./install.sh
fi
