#!/usr/bin/env bash
#
# Summary: Execute a command for each Julia version
#
# Usage: jlenv each [-v] <command> [arg1 arg2...]
#
# Executes a command for each Julia version by setting JLENV_VERSION.
# Failures are collected and reported at the end.
#
#    -v  Verbose mode. Prints a header for each Julia.
#
# For more information on jlenv-each, see:
# https://github.com/jlenv/jlenv-each#readme

set -e
[ -n "$JLENV_DEBUG" ] && set -x

# Provide jlenv completions
case "$1" in
  --complete )
    echo --help
    echo --verbose
    exit
    ;;
  -v | --verbose )
    verbose=1
    shift
    ;;
  --help )
    jlenv-help each
    exit
    ;;
  ""  | -* )
    jlenv-help --usage each >&2
    exit 1
    ;;
esac

if [ "$1" = "--version" ] || [ "$1" = "-v" ]; then
  echo "jlenv-each 1.0.0"
  exit
fi

GRAY=""
RED=""
YELLOW=""
NORMAL=""

if [ -t 1 ]; then
  GRAY="\033[1;30m"
  RED="\033[0;31m"
  YELLOW="\033[0;33m"
  NORMAL='\033[0m'
fi

falied_julies=''

trap "exit 1" INT

for julia in $(jlenv versions --bare --skip-aliases); do
  if [ -n "$verbose" ]; then
    header="===[$julia]==================================================================="
    header="${header:0:72}"
    header="${header/[/[${YELLOW}}"
    header="${header/]/${GRAY}]}"
    echo -e "${GRAY}${header}${NORMAL}"
  fi

  JLENV_VERSION="$julia" "$@" || falied_julies="$falied_julies $julia"

  [ -n "$verbose" ] && echo
done

if [ -n "$falied_julies" ]; then
  echo -e "${RED}FAILED IN:${falied_julies}${NORMAL}"
  exit 1
fi
